
export interface Track {
  id: string;        
  title: string;     
  artist: string;    
  duration?: number; 
}

export type MoodPlaylist = Track[];

export interface MoodPlaylists {
  sad: MoodPlaylist;
  calm: MoodPlaylist;
  romantic: MoodPlaylist;
  happy: MoodPlaylist;
  energetic: MoodPlaylist;
}

export const MOOD_PLAYLISTS: MoodPlaylists = {
  sad: [
    { id: "nyuo9-OjNNg", title: "I Wanna Be Yours", artist: "Unknown Artist" },
    { id: "nOeJuoFs6sM", title: "КАМИН", artist: "EMIN feat. JONY" },
    { id: "-TXtyYZIiWc", title: "Pastlives", artist: "sapientdream" },
    { id: "WQq98YPV8yk", title: "Moral of the Story", artist: "Ashe" },
    { id: "PcCD9n0ZYew", title: "Tattoo", artist: "Loreen" },
    { id: "Gwg_KYNgu6Y", title: "Into Your Arms  ft. Ava Max - [No Rap]", artist: "Witt Lowry" },
    { id: "RgKAFK5djSk", title: "See You Again ft. Charlie Puth  Furious 7 Soundtrack", artist: "Wiz Khalifa" },
    { id: "DKbfBSrjVHA", title: "Can We Kiss Forever?  ft. Adriana Proenza", artist: "Kina" },
    { id: "rtOvBOTyX00", title: "A Thousand Years", artist: "Christina Perri" },
    { id: "PNozaFzqOvI", title: "Arcade  ft. FLETCHER", artist: "Duncan Laurence" },
    { id: "hT_nvWreIhg", title: "Counting Stars", artist: "OneRepublic" },
    { id: "VbfpW0pbvaU", title: "Stitches", artist: "Shawn Mendes" },
    { id: "RBumgq5yVrA", title: "Let Her Go", artist: "Passenger" },
    { id: "4fqwVBuunxY", title: "Hurts So Good", artist: "Astrid S" },
    { id: "60ItHLz5WEA", title: "Faded", artist: "Alan Walker" },
    { id: "V1Pl8CzNzCw", title: "lovely", artist: "Billie Eilish, Khalid" },
    { id: "ALZHF5UqnU4", title: "Alone", artist: "Marshmello" },
    { id: "ZAfAud_M_mg", title: "Without Me", artist: "Halsey" },
    { id: "syFZfO_wfMQ", title: "Night Changes", artist: "One Direction" },
    { id: "lY2yjAdbvdQ", title: "Treat You Better", artist: "Shawn Mendes" },
    { id: "5-ZiKXrnvog", title: "MIIA", artist: "Dynasty" },
    { id: "tt2k8PGm-TI", title: "Dusk Till Dawn  ft. Sia", artist: "ZAYN" },
    { id: "GCdwKhTtNNw", title: "Sweater Weather", artist: "The Neighbourhood" },
    { id: "LHCob76kigA", title: "7 Years", artist: "Lukas Graham" },
    { id: "kPa7bsKwL-c", title: "Die With A Smile", artist: "Lady Gaga, Bruno Mars" },
    { id: "5FSHSfSnjXk", title: "Carpetman – What Does It Mean To You", artist: "Unknown Artist" },
    { id: "qN4ooNx77u0", title: "Sign of the Times", artist: "Harry Styles" },
    { id: "L7mfjvdnPno", title: "Falling", artist: "Trevor Daniel" },
    { id: "mRD0-GxqHVo", title: "Heat Waves", artist: "Glass Animals" },
    { id: "SkcO47UDzzY", title: "LET THE WORLD BURN", artist: "Chris Grey" },
    { id: "jJPMnTXl63E", title: "death bed (coffee for your head)  ft. beabadoobee", artist: "Powfu" },
    { id: "TdrL3QxjyVw", title: "Summertime Sadness", artist: "Lana Del Rey" },
    { id: "WgTMeICssXY", title: "Dandelions", artist: "Ruth B." },
    { id: "f0bbDFRYD_A", title: "changes", artist: "XXXTENTACION" },
    { id: "d_HlPboLRL8", title: "Runaway", artist: "AURORA" },
    { id: "8ofCZObsnOo", title: "Hold On", artist: "Chord Overstreet" },
    { id: "GPvBmcoriNo", title: "Alone, Pt. II", artist: "Alan Walker & Ava Max" },
    { id: "cHHLHGNpCSA", title: "Waiting For Love", artist: "Avicii" },
    { id: "Oextk-If8HQ", title: "Somewhere Only We Know", artist: "Keane" },
    { id: "I-QfPUz1es8", title: "Bad Liar", artist: "Imagine Dragons" },
    { id: "GxldQ9eX2wo", title: "Until I Found You", artist: "Stephen Sanchez" },
    { id: "yctQRe--q6c", title: "Love Is Gone (ft. Dylan Matthew)", artist: "SLANDER" },
    { id: "Qzc_aX8c8g4", title: "Dancing With Your Ghost", artist: "Sasha Alex Sloan" },
    { id: "a5uRyaThmLo", title: "WHEN I'M WITH YOU FT. NEVERWAVES", artist: "SLANDER & SYNYMATA" },
    { id: "KyAcMpQUY5s", title: "Hope", artist: "Unknown Artist" },
    { id: "LTMjsgS_c9M", title: "Hislerim (feat. Zerrin) 🇹🇷", artist: "Serhat Durmus" },
    { id: "IpFX2vq8HKw", title: "blue", artist: "yung kai" },
    { id: "WjqYTpE6Qdg", title: "Set Fire to the Rain", artist: "Adele" },
    { id: "Uefu_EU-dW4", title: "Middle of the Night", artist: "Elley Duhé" },
    { id: "DF3XjEhJ40Y", title: "Love Story", artist: "Indila" },
    { id: "Jtauh8GcxBY", title: "Before You Go", artist: "Lewis Capaldi" },
    { id: "PaKr9gWqwl4", title: "Only Love Can Hurt Like This", artist: "Paloma Faith" },
    { id: "ixRLjjTRczE", title: "Another Love", artist: "Tom Odell" },
    { id: "l08Zw-RY__Q", title: "WILDFLOWER", artist: "Billie Eilish" },
    { id: "OlStmta0Vh4", title: "I Was Never There feat. Gesaffelstein", artist: "The Weeknd" },
    { id: "PWqEPKduGm8", title: "Infinity", artist: "Jaymes Young" },
    { id: "28W_sotzXUw", title: "La Câlin (Obiymy)", artist: "Serhat Durmus" },
    { id: "m-el0pQLQE4", title: "childhood", artist: "Rauf & Faik" },
    { id: "EKkzbbLYPuI", title: "Carol of the Bells", artist: "Lindsey Stirling" },
    { id: "lW9ep22YmlM", title: "Royalty (ft. Neoni)", artist: "Egzod & Maestro Chives" },
    { id: "hbqoaJ8sKsQ", title: "Broken Angel", artist: "Arash feat. Helena" },
    { id: "y7T3ax7JPwI", title: "Peaky Blinder  | i am not outsider i'm a peaky blinder", artist: "Otnicka" },
    { id: "oewANcF6hVY", title: "колыбельная", artist: "Rauf & Faik" },
    { id: "BqvAMjH0nic", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "rpdFcQbZ2TI", title: "Into Your Arms x Alone, Pt. II (Music Video)", artist: "Ava Max" },
    { id: "oQ0wldvLzc0", title: "Rauf & Faik   это ли счастье?", artist: "Unknown Artist" },
    { id: "1G4isv_Fylg", title: "Paradise", artist: "Coldplay" },
    { id: "g5FoAy5C5z0", title: "Can't Buy Me Loving / La La La (это ли счастье ?)", artist: "Rauf & Faik" },
    { id: "T3jEVMTw6tM", title: "WASTE", artist: "Kxllswxtch" },
    { id: "jKRW9ZV8QzI", title: "Those Eyes (Sped Up)", artist: "Unknown Artist" },
    { id: "m7Bc3pLyij0", title: "Happier", artist: "Marshmello ft. Bastille" },
    { id: "E6ojldjb0Ug", title: "Headphones (Heyson Remix)", artist: "Unknown Artist" },
  ],

  calm: [
    { id: "lbjZPFBD6JU", title: "Come Away With Me", artist: "Norah Jones" },
    { id: "E3iq2GS0B80", title: "Bryan Ferry – Slave To Love (piano and vocal cover)", artist: "Unknown Artist" },
    { id: "bPCdsa7hS7M", title: "Watermark", artist: "Enya" },
    { id: "7maJOI3QMu0", title: "River Flows in You", artist: "Yiruma, (이루마)" },
    { id: "rOLN9T9w9kA", title: "The Sea", artist: "Unknown Artist" },
    { id: "1jNNwbuDXsA", title: "Feel So High", artist: "Des'ree" },
    { id: "QQ84s2uzZ1w", title: "Ocean Drive", artist: "Lighthouse Family" },
    { id: "Rk_sAHh9s08", title: "Return To Innocence", artist: "Enigma" },
    { id: "KLVq0IAzh1A", title: "Fields Of Gold", artist: "Sting" },
    { id: "bTNLYeaL7No", title: "Songbird", artist: "Eva Cassidy" },
    { id: "Jl8iYAo90pE", title: "Caribbean Blue (Official  Music Video)", artist: "Enya" },
    { id: "MEO6gYCFbr0", title: "Sailing", artist: "Christopher Cross" },
    { id: "Ftco75S7ZqE", title: "Spirit Dances", artist: "Kashy Keegan" },
    { id: "dVNdTXEJv1A", title: "Pure Shores", artist: "All Saints" },
    { id: "1TO48Cnl66w", title: "Thank You", artist: "Dido" },
    { id: "fd02pGJx0s0", title: "Sunrise", artist: "Norah Jones" },
    { id: "rrPUJsZQSkw", title: "Nine Million Bicycles  ( Remaster)", artist: "Katie Melua" },
    { id: "LTrk4X9ACtw", title: "Orinoco Flow (Official  Music Video)", artist: "Enya" },
    { id: "j-fWDrZSiZs", title: "White Flag", artist: "Dido" },
    { id: "DmAOBosGlHY", title: "Yusuf / Cat Stevens – Morning Has Broken", artist: "Unknown Artist" },
    { id: "rjOhZZyn30k", title: "Put Your Records On", artist: "Corinne Bailey Rae" },
    { id: "KPctA0hT9c8", title: "Peaceful Easy Feeling (2013 Remaster)", artist: "Unknown Artist" },
    { id: "VqhCQZaH4Vs", title: "What A Wonderful World", artist: "Louis Armstrong" },
    { id: "QDYfEBY9NM4", title: "Let It Be ( 2009)", artist: "Unknown Artist" },
    { id: "d-diB65scQU", title: "Don't Worry Be Happy", artist: "Bobby McFerrin" },
    { id: "flHo2LFWh2I", title: "Serenity", artist: "Kashy Keegan" },
    { id: "GemKqzILV4w", title: "Chasing Cars", artist: "Snow Patrol" },
    { id: "2rd8VktT8xY", title: "Over The Rainbow (Blues Alley performance)", artist: "Eva Cassidy" },
    { id: "mer6X7nOY_o", title: "Somewhere Only We Know (John Lewis Christmas Advert)", artist: "Lily Allen" },
    { id: "tO4dxvguQDk", title: "Don't Know Why", artist: "Norah Jones" },
  ],

  romantic: [
    { id: "kPa7bsKwL-c", title: "Die With A Smile", artist: "Lady Gaga, Bruno Mars" },
    { id: "pyGU-UudvrM", title: "I Thought I Saw Your Face Today", artist: "She & Him" },
    { id: "GxldQ9eX2wo", title: "Until I Found You", artist: "Stephen Sanchez" },
    { id: "lY5V4hSLWY8", title: "Risk It All", artist: "Bruno Mars" },
    { id: "jXqf3uqLkkU", title: "Eternity", artist: "Alex Warren" },
    { id: "r0c9Q21AfLA", title: "Belong Together (Official Visualizer)", artist: "Mark Ambor" },
    { id: "e1mOmdykmwI", title: "I Think They Call This Love", artist: "Elliot James Reay" },
    { id: "xLYtdCdkuMI", title: "we hug now", artist: "sydney rose" },
    { id: "tKml80alH3Y", title: "Stargazing", artist: "Myles Smith" },
    { id: "vx4kLgnFexo", title: "My Love Mine All Mine", artist: "Mitski" },
    { id: "fukGbiPuBjU", title: "I Wanna Be Yours", artist: "Arctic Monkeys" },
    { id: "KZCGhO3t0DA", title: "Scared To Start", artist: "Michael Marcagi" },
    { id: "d4iGZ_jP-1U", title: "Carry You Home", artist: "Alex Warren" },
    { id: "aKuNwPYACVE", title: "Espresso", artist: "Sabrina Carpenter" },
    { id: "_-YjO6KfEMk", title: "Those Eyes", artist: "New West" },
    { id: "Ms-xidSx0Ek", title: "Cozy", artist: "Jeremy Zucker, Lauv, Alexander 23" },
    { id: "u2ah9tWTkmk", title: "Ordinary", artist: "Alex Warren" },
    { id: "pVi9W3OThVw", title: "Teenage Dream", artist: "Stephen Dawes" },
    { id: "57VMB1IzLKY", title: "Stumblin' In", artist: "CYRIL" },
    { id: "EzQ-KpvHm60", title: "The Ballet Girl", artist: "Aden Foyer" },
    { id: "jKIEUdAMtrQ", title: "Minefields", artist: "Faouzia & John Legend" },
    { id: "LPgN4EfzUrU", title: "Calm Down", artist: "Rema & Selena Gomez" },
    { id: "8hLtlzkoGPk", title: "Hold Me Closer", artist: "Elton John, Britney Spears" },
    { id: "hKgl5-lkT8U", title: "Best Part, a Visual", artist: "Daniel Caesar & H.E.R." },
    { id: "DIKIgjLGf98", title: "Snap -", artist: "Rosa Linn" },
    { id: "m7XGWGFgQVA", title: "Somebody's Pleasure", artist: "Aziz Hedra" },
    { id: "2qzcHLyv3N0", title: "The Joker And The Queen (feat. Taylor Swift)", artist: "Ed Sheeran" },
    { id: "OM5cVB81aT8", title: "Hero", artist: "Charlie Puth" },
    { id: "pkDpOIjCJ78", title: "Stars in the Sky", artist: "Alexia" },
    { id: "1jO2wSpAoxA", title: "If the World Was Ending  ft. Julia Michaels", artist: "JP Saxe" },
    { id: "FgS1b2nU8AQ", title: "Sex, Drugs, Etc.", artist: "Beach Weather" },
    { id: "ODDRRXMi22E", title: "i like the way you kiss me", artist: "Artemas" },
    { id: "H5v3kku4y6Q", title: "As It Was", artist: "Harry Styles" },
    { id: "NKzd_YiW9AQ", title: "What If I Told You That I Love You", artist: "Ali Gatie" },
    { id: "8CEJoCr_9UI", title: "At My Worst", artist: "Pink Sweat$" },
    { id: "uPD0QOGTmMI", title: "Die For You", artist: "The Weeknd" },
    { id: "jRLLWQCOKV4", title: "Lovesong (Official Live Video)", artist: "beabadoobee" },
    { id: "CMWLX0KXwF4", title: "No One Dies From Love", artist: "Tove Lo" },
    { id: "Aw1eOFJiDtE", title: "Fall In Love Alone", artist: "Stacey Ryan" },
    { id: "H1hDzq98WIY", title: "Love Me More", artist: "Sam Smith" },
    { id: "cvCgv775KRs", title: "Anyone (On The Road)", artist: "Justin Bieber" },
    { id: "dgmjeMo_pDY", title: "Line By Line (feat. Maren Morris)", artist: "JP Saxe, Maren Morris" },
    { id: "ZmDBbnmKpqQ", title: "drivers license", artist: "Olivia Rodrigo" },
    { id: "ruHUEmDfw6A", title: "Scared of Love (Official Music Video with )", artist: "Ali Gatie" },
    { id: "yg6Y_1_DJyI", title: "Hot Stuff", artist: "Kygo, Donna Summer" },
    { id: "vLfxCE6Vofw", title: "you", artist: "CKay" },
    { id: "lznH7FZBBYs", title: "All We Got", artist: "Robin Schulz feat. KIDDO" },
    { id: "irQzUJK7zdE", title: "Heaven", artist: "Pink Sweat$" },
    { id: "Dbx0ryKmmnc", title: "Too Close", artist: "JP Cooper" },
    { id: "7Lna4Hu4-AQ", title: "Butterflies", artist: "MAX & Ali Gatie" },
    { id: "g5T2tu3Yky4", title: "Shadow Of Mine", artist: "Alec Benjamin" },
    { id: "H5RpMywlZ2Q", title: "Sugar Sweet", artist: "Benson Boone" },
    { id: "jr47YisIsz8", title: "We're Good", artist: "Dua Lipa" },
    { id: "NmB9Rq1yVmo", title: "I Love U", artist: "The Chainsmokers" },
    { id: "h5WN3pkxPF0", title: "Baila Conmigo", artist: "Selena Gomez, Rauw Alejandro" },
    { id: "8RvAKRoIDqU", title: "Diamonds", artist: "Sam Smith" },
    { id: "pk1btLJQjTw", title: "Your Love (9PM)", artist: "ATB x Topic x A7S" },
    { id: "V39V9rQxImc", title: "teo glacier – close with desires", artist: "Unknown Artist" },
    { id: "_bptrMV3zHE", title: "You're Mines Still (feat. Drake)", artist: "Yung Bleu" },
    { id: "ZW5LkUnCoSE", title: "New Love (feat. Ellie Goulding)", artist: "Silk City" },
    { id: "aXzVF3XeS8M", title: "Love Story (Taylor’s Version)", artist: "Taylor Swift" },
    { id: "fz78HOxOgEY", title: "Stuck With U", artist: "Ariana Grande, Justin Bieber" },
    { id: "piOIvNO2M8Q", title: "ily (i love you baby) (feat. Emilee)", artist: "Surf Mesa" },
    { id: "nbc7S3hWlgk", title: "Lovefool", artist: "twocolors" },
    { id: "Pkh8UtuejGw", title: "Señorita", artist: "Shawn Mendes, Camila Cabello" },
    { id: "mYADDo7x83o", title: "Hey Stupid, I Love You", artist: "JP Saxe" },
    { id: "VF-r5TtlT9w", title: "Adore You", artist: "Harry Styles" },
    { id: "24u3NoPvgMw", title: "Heather", artist: "Conan Gray" },
    { id: "2Vv-BfVoq4g", title: "Perfect", artist: "Ed Sheeran" },
    { id: "450p7goxZqg", title: "All of Me", artist: "John Legend" },
    { id: "JGwWNGJdvx8", title: "Shape of You", artist: "Ed Sheeran" },
    { id: "AJtDXIazrMo", title: "Love Me Like You Do", artist: "Ellie Goulding" },
    { id: "bo_efYhYU2A", title: "Shallow (from A Star Is Born)", artist: "Lady Gaga, Bradley Cooper" },
    { id: "lWA2pjMjpBs", title: "Diamonds", artist: "Rihanna" },
    { id: "Y2E71oe0aSM", title: "10,000 Hours", artist: "Dan + Shay, Justin Bieber" },
    { id: "pjTj-_55WZ8", title: "These Days (feat. Jess Glynne, Macklemore & Dan Caplen)", artist: "Rudimental" },
    { id: "LAdxhHz6Tu4", title: "Love Again (Official  Video)", artist: "Dua Lipa" },
    { id: "RtlOk0Kz5gQ", title: "It's You", artist: "Ali Gatie" },
    { id: "lwGEhnl0NxQ", title: "Wait for You", artist: "Tom Walker" },
    { id: "n-D1EB74Ckg", title: "Come & Get It", artist: "Selena Gomez" },
    { id: "g5qU7p7yOY8", title: "Love Me Harder", artist: "Ariana Grande, The Weeknd" },
    { id: "V1bFr2SWP1I", title: 'Israel "IZ" Kamakawiwoʻole', artist: "OFFICIAL Somewhere over the Rainbow" },
    { id: "nmjdaBaZe8Y", title: "With You", artist: "Chris Brown" },
    { id: "nIjVuRTm-dc", title: "She Will Be Loved", artist: "Maroon 5" },
    { id: "koJlIGDImiU", title: "Hero", artist: "Enrique Iglesias" },
    { id: "vhCEaGWTu10", title: "Wherever You Are", artist: "Kodaline" },
    { id: "qUD2GxTeVcI", title: "Conversations in the Dark", artist: "John Legend" },
    { id: "ONS51QzCh1Y", title: "Finally // beautiful stranger", artist: "Halsey" },
    { id: "SlPhMPnQ58k", title: "Memories", artist: "Maroon 5" },
    { id: "qz7tCZE_3wA", title: "Can We Kiss Forever? (ft. Adriana Proenza)", artist: "Kina" },
    { id: "yG60iRJwmfA", title: "Sucker", artist: "Jonas Brothers" },
    { id: "vtcBNdIq1ms", title: "I Belong to You", artist: "Jacob Lee" },
    { id: "vxQO3i5g48I", title: "WAIT", artist: "Hunter Hayes" },
    { id: "muPO1c6pxXg", title: "Snooze (Acoustic)  ft. Justin Bieber", artist: "SZA" },
    { id: "V3IVdLo-2NM", title: "feelslikeimfallinginlove", artist: "Coldplay" },
    { id: "zfbIWWZdtoE", title: "Life With You", artist: "Kelsey Hart" },
    { id: "msGuqelopMA", title: "DAISIES", artist: "Justin Bieber" },
    { id: "O8WXFI_MSAI", title: "Camera", artist: "Ed Sheeran" },
    { id: "1lrFsXkT_rM", title: "Sailor Song", artist: "Gigi Perez" },
    { id: "1FVF-9KQiPo", title: "Opalite", artist: "Taylor Swift" },
  ],

  happy: [
    { id: "LnHZ7_1_LVE", title: "Dan + Shay, Justin Bieber", artist: "10,000 Hours" },
    { id: "qxCCGcMC1Jk", title: "2002", artist: "Anne-Marie" },
    { id: "bnVkf-z28YU", title: "I Like Me Better", artist: "Lauv" },
    { id: "dW1bkAR1UC4", title: "Capital Letters ( /  Video)", artist: "Hailee Steinfeld, BloodPop®" },
    { id: "74yb9E3WY1I", title: "Beautiful People (feat. Khalid)", artist: "Ed Sheeran" },
    { id: "LJrejf8blAA", title: "ME!  Ft. Brendon Urie", artist: "Taylor Swift" },
    { id: "0m9icI0AOhw", title: "Perfect To Me", artist: "Anne-Marie" },
    { id: "9TktpJyH58I", title: "Why Don't We ‒ Big Plans", artist: "Unknown Artist" },
    { id: "vis3dxQ0rQs", title: "JAMES TW", artist: "SAY LOVE" },
    { id: "CCSGelSCPGE", title: "I Don't Care", artist: "Ed Sheeran & Justin Bieber" },
    { id: "ow1QqW0jzTo", title: "Señorita", artist: "Shawn Mendes, Camila Cabello" },
    { id: "cMqal8F3Ef4", title: "Never Really Over", artist: "Katy Perry" },
    { id: "7bwzasTLOuo", title: "This Feeling  ft. Kelsea Ballerini", artist: "The Chainsmokers" },
    { id: "UTz2tOSXt2U", title: "Sucker for you  (Mr. Stubborn)", artist: "Matt Terry" },
    { id: "rn4cNk0f73g", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "q07RanslaGM", title: "South of the Border (feat. Camila Cabello & Cardi B)", artist: "Ed Sheeran" },
    { id: "yTtcaBZt6ow", title: "Chasing Fire", artist: "Lauv" },
    { id: "9oBZpybMQTE", title: "17", artist: "Julia Michaels" },
    { id: "KCIKbE_N_DU", title: "I Forgot That You Existed", artist: "Taylor Swift" },
    { id: "LS2ifrLAadU", title: "Stay  🎤", artist: "Zedd, Alessia Cara" },
    { id: "miDfTKlmD6M", title: "What Lovers Do  feat. SZA", artist: "Maroon 5" },
    { id: "E5FZMjWOxpU", title: "Sixteen", artist: "Ellie Goulding" },
    { id: "vVqGNfAZb2w", title: "Liar", artist: "Camila Cabello" },
    { id: "i95Nlb7kiPo", title: "Your Song", artist: "Rita Ora" },
    { id: "VJzcoGmcxEc", title: "She Looks So Perfect", artist: "5SOS" },
    { id: "CEkTYUe_-cA", title: "Get To Know You (  )", artist: "Samantha Harvey" },
    { id: "SY3qEbhZhFA", title: "Let It Be Me", artist: "Steve Aoki & Backstreet Boys" },
    { id: "bsSK1DccV_Y", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "eY4t1Scl6LQ", title: "LET YOU LOVE ME", artist: "Rita Ora" },
    { id: "GQrIiqPQ-KY", title: "Takeaway  ft. Lennon Stella", artist: "The Chainsmokers, Illenium" },
    { id: "0_6j0Fi0-LM", title: "Good As Hell", artist: "Lizzo, Ariana Grande" },
    { id: "ClhLNUPqv8Q", title: "Dua Lipa ‒ New Rules  🎤", artist: "Unknown Artist" },
    { id: "lKdOW0OOBaE", title: "Your Side Of The Bed ( / Lyric Video)", artist: "Loote" },
    { id: "J1kjdF1nICE", title: "La Di Da", artist: "Lennon Stella" },
    { id: "W3fJk1rHOOk", title: "123", artist: "Jess Glynne" },
    { id: "CVhJYPNK6sI", title: "Don't Start Now", artist: "Dua Lipa" },
    { id: "tRwMD-hCtjk", title: "Walk Off the Earth", artist: "I'll Be There" },
    { id: "IZ_QRBCQxa8", title: "Younger", artist: "Jonas Blue & HRVY" },
    { id: "HOSzxbQOImA", title: "The Vamps – Shivers", artist: "Unknown Artist" },
    { id: "UlXPdOuNU3Q", title: "These Days  Ft. Jess Glynne, Macklemore & Dan Caplen", artist: "Rudimental" },
    { id: "1RNXYIsmbeY", title: "If You're Over Me", artist: "Years & Years" },
    { id: "YEWJ3E50pC4", title: "What I Like About You  ft. Theresa Rex", artist: "Jonas Blue" },
    { id: "MrbHZkHimbo", title: "King Princess", artist: "1950" },
    { id: "0ECuBsqUR7Q", title: "Can We Pretend  ft. Cash Cash", artist: "P!nk" },
    { id: "8KbUubuELPs", title: "Jesus In LA", artist: "Alec Benjamin" },
    { id: "YiDeezkO7m8", title: "One Touch", artist: "Jess Glynne, Jax Jones" },
    { id: "dusDiKHrCk4", title: "Westlife-World Of Our Own  []", artist: "Unknown Artist" },
    { id: "1H1iysBAzCc", title: "Always you with", artist: "Unknown Artist" },
    { id: "iFJdHDE9cgs", title: "All The Lies", artist: "Alok, Felix Jaehn & The Vamps" },
    { id: "gXvczijTQSQ", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "58VNvx4oLXI", title: "Ooh Girl  ft. A Boogie Wit da Hoodie", artist: "Kris Kross Amsterdam & Conor Maynard" },
    { id: "AWxUUTQBZR8", title: "When You're Looking Like That", artist: "Westlife" },
    { id: "fuI0bEdoF30", title: "Keep You Mine", artist: "NOTD, Shy Martin" },
    { id: "fU4kTYsCyxU", title: "Yung Luv ( /  Video)", artist: "Andrelli, Hearts & Colors" },
    { id: "7oBU7d5oenQ", title: "Good Time", artist: "Owl City, Carly Rae Jepsen" },
    { id: "7EwBuptpfx4", title: "Rhys", artist: "Too Good To Be True" },
    { id: "jRbbFb0jnm8", title: "Lost (feat. Clean Bandit)", artist: "End of the World" },
    { id: "Y7ix6RITXM0", title: "Maps", artist: "Maroon 5" },
    { id: "digUx01moDE", title: "Ooh La La", artist: "Josie Dunne" },
    { id: "UFyR8VWImhQ", title: "Connection", artist: "OneRepublic" },
    { id: "29O6jyi4n-8", title: "Medicine", artist: "Robinson" },
    { id: "m3ycpcWapXk", title: "Headlights", artist: "Hellberg, Leona Lewis" },
    { id: "Y-Wqna-hC2Y", title: "Let It Be Me  ft. Ava Max", artist: "David Guetta" },
    { id: "xL2VMBNBAkY", title: "Bad Vibrations", artist: "A Day To Remember" },
    { id: "tTSjI-_RwEE", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "rF53erGQs6c", title: "Somebody", artist: "Sigala, HRVY, Nina Nesbitt" },
    { id: "mG6UX2-JJek", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "nGGTnNkaZAg", title: "Never Knew", artist: "Layton Greene" },
    { id: "teU3AhSjYv0", title: "John De Sohn – Love You Better  ft. Rasmus Hagen", artist: "Unknown Artist" },
    { id: "GY_XRuckkR0", title: "Somebody I'm Not", artist: "Martin Jensen, Bjørnskov" },
    { id: "O961svr0RVY", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "i_ZUBj2xeq8", title: "Ready To Love You", artist: "HEDEGAARD" },
    { id: "1Qit1aj6z8U", title: "Paradise to Me", artist: "Niko Moon" },
    { id: "UW5SMrURVbM", title: "Unknown Title", artist: "Unknown Artist" },
    { id: "mk48xRzuNvA", title: "Hall of Fame  ft. will.i.am", artist: "The Script" },
    { id: "L68gl3VfZZQ", title: "Wanted", artist: "NOTD & Daya" },
    { id: "QG0tei7zQX8", title: "Whenever  feat. Conor Maynard", artist: "Kris Kross Amsterdam x The Boy Next Door" },
    { id: "P466Nq-kjY4", title: "Hot N'Cold", artist: "Katy Perry" },
    { id: "1hZSulcsImQ", title: "My Girl", artist: "The Temptations" },
    { id: "CJqILnpKdxk", title: "Clearly", artist: "Grace VanderWaal" },
    { id: "OVFwTEbjNxU", title: "Lady", artist: "Blake Rose" },
    { id: "0-CYcrmGBZU", title: "Remind Me To Forget ( / Lyric Video) ft. Miguel", artist: "Kygo" },
    { id: "oGxXyxmynGs", title: "Hold My Hand", artist: "Jess Glynne" },
    { id: "j7QUvzX4Mt0", title: "Move On", artist: "Mike Posner" },
    { id: "M8w-4JEl06I", title: "Faustix & Shannon Rani", artist: "Crying In The Sun" },
    { id: "uMHY3gT38KI", title: "Endless Summer  ft. Kiddo AI", artist: "CASHAE" },
    { id: "OnKl3g3NGDk", title: "Family", artist: "The Chainsmokers & Kygo" },
    { id: "CCED4g1dMTQ", title: "Build Me Up Buttercup by The Foundations with", artist: "Unknown Artist" },
    { id: "FBxR2uxXcto", title: "Dancing In The Moonlight  (feat. NEIMY)", artist: "Jubel" },
    { id: "0fTUj9mfnUk", title: "American Authors", artist: "Best Day of My Life" },
    { id: "gDhlk7IhZqA", title: "Back Together", artist: "Loote" },
    { id: "i9qjQq8gT68", title: "Best Of Me (FGL Official )", artist: "Blake Rose" },
    { id: "mFs42JgOBZo", title: "Wanted", artist: "NOTD & Daya" },
    { id: "moKoAUZ25lk", title: "Free Rein Opening - Basic Tape VS Frances", artist: "No Matter" },
    { id: "opPV1-IUmGw", title: "Coldplay", artist: "Viva la Vida" },
  ],

  energetic: [
    { id: "Fplgu4VVb94", title: "Stargazing", artist: "Unknown Artist" },
    { id: "wd9_QCH8Eq4", title: "Don't Start Now", artist: "Unknown Artist" },
    { id: "eleP7yc9dSY", title: "Espresso", artist: "Unknown Artist" },
    { id: "MpOvl2zZscQ", title: "Fortnight (BLOND:ISH Remix)", artist: "Unknown Artist" },
    { id: "Hx4nWW9z0ig", title: "Dance Monkey", artist: "Unknown Artist" },
    { id: "peLRPSCeppI", title: "Moth To A Flame", artist: "Unknown Artist" },
    { id: "xBKiqNAcCBs", title: "Makeba (Ian Asher Remix)", artist: "Unknown Artist" },
    { id: "C0k6USrt408", title: "Don't Be Shy", artist: "Unknown Artist" },
    { id: "gvL1Bz2QVLY", title: "Dance With Me", artist: "Unknown Artist" },
    { id: "owTWCbq_nSk", title: "Something Just Like This", artist: "Unknown Artist" },
    { id: "njvA03rMHx4", title: "Safe And Sound", artist: "Unknown Artist" },
    { id: "jVBsM8CM0AE", title: "i like the way you kiss me", artist: "Unknown Artist" },
    { id: "J7p4bzqLvCw", title: "Blinding Lights", artist: "Unknown Artist" },
    { id: "8VKD-IlvibI", title: "Unholy", artist: "Unknown Artist" },
    { id: "950BdJKBhGo", title: "Shut Down", artist: "Unknown Artist" },
    { id: "jPe0bX_GtBo", title: "INDUSTRY BABY", artist: "Unknown Artist" },
    { id: "G1ej5up7JG0", title: "Shivers", artist: "Unknown Artist" },
    { id: "Z1yDjhXIDSc", title: "Dance The Night (From Barbie The Album)", artist: "Unknown Artist" },
    { id: "2NiyrtYegso", title: "Wake Me Up", artist: "Unknown Artist" },
    { id: "ZD6rXLXZOEI", title: "bad guy", artist: "Unknown Artist" },
    { id: "HaEYUJ2aRHs", title: "Dynamite", artist: "Unknown Artist" },
    { id: "hJWSZDJb-W4", title: "Bad Habits", artist: "Unknown Artist" },
    { id: "ui7M7j7caHA", title: "Kiss Me More", artist: "Unknown Artist" },
    { id: "e8WoWk4b3D0", title: "Levitating (feat. DaBaby)", artist: "Unknown Artist" },
    { id: "4zsVKROnQfY", title: "MIDDLE OF THE NIGHT", artist: "Unknown Artist" },
    { id: "XZ868t23Pb4", title: "7 rings", artist: "Unknown Artist" },
    { id: "Ztdc7TcPdAA", title: "There's Nothing Holdin' Me Back", artist: "Unknown Artist" },
    { id: "xTvyyoF_LZY", title: "Shape of You", artist: "Unknown Artist" },
    { id: "CpTr4USXjQw", title: "Don't Let Me Down", artist: "Unknown Artist" },
    { id: "e-S1k9-soT4", title: "Cold Heart (PNAU Remix)", artist: "Unknown Artist" },
    { id: "n-UIRqgXjGA", title: "I Like You (A Happier Song)", artist: "Unknown Artist" },
    { id: "_GWKkqNoyEA", title: "Counting Stars", artist: "Unknown Artist" },
    { id: "TaZkqPK0sbw", title: "My Universe", artist: "Unknown Artist" },
    { id: "inCm3ByI17o", title: "This Is What You Came For", artist: "Unknown Artist" },
    { id: "_GX3D32b3TI", title: "STAR WALKIN' (League of Legends Worlds Anthem)", artist: "Unknown Artist" },
    { id: "r7zTKRonHXM", title: "Closer", artist: "Unknown Artist" },
    { id: "ntG3GQdY_Ok", title: "Light Switch", artist: "Unknown Artist" },
    { id: "88ft3GeEsto", title: "Miss You", artist: "Unknown Artist" },
    { id: "Yw-vvxnG9Y4", title: "Burn", artist: "Unknown Artist" },
    { id: "ZqYGW8uXL0I", title: "New Rules", artist: "Unknown Artist" },
    { id: "0ZwRIThLxGA", title: "Vegas (From the Original Motion Picture Soundtrack ELVIS)", artist: "Unknown Artist" },
    { id: "wnWxeBfV2ZQ", title: "About Damn Time", artist: "Unknown Artist" },
    { id: "v16qZcBllUU", title: "Sorry", artist: "Unknown Artist" },
    { id: "NaaiI1y9QIo", title: "Break My Heart", artist: "Unknown Artist" },
    { id: "tYvFa2ARD24", title: "Uptown Funk", artist: "Unknown Artist" },
    { id: "tWIJFhZ69_U", title: "The Motto", artist: "Unknown Artist" },
    { id: "sWMk8dwljFU", title: "Shake It Off", artist: "Unknown Artist" },
    { id: "y4FiCl-tUJc", title: "Demons", artist: "Unknown Artist" },
    { id: "NNCBq0JHXsU", title: "Butter", artist: "Unknown Artist" },
    { id: "XWCPbRsMb0Q", title: "One Kiss", artist: "Unknown Artist" },
    { id: "mG5jXd3MlE0", title: "feelslikeimfallinginlove", artist: "Unknown Artist" },
    { id: "c5l4CGQozWY", title: "Work from Home", artist: "Unknown Artist" },
    { id: "f0dYb6nrVY4", title: "Ferrari", artist: "Unknown Artist" },
    { id: "6nJuUdc2qNg", title: "Roar", artist: "Unknown Artist" },
    { id: "LRPGqNeav_M", title: "Titanium (feat. Sia)", artist: "Unknown Artist" },
    { id: "Yegn0dZ-BfY", title: "Physical", artist: "Unknown Artist" },
    { id: "n6N1_sxlBU8", title: "We Found Love", artist: "Unknown Artist" },
    { id: "mVw5KiGwqaQ", title: "Rockabye (feat. Sean Paul & Anne-Marie)", artist: "Unknown Artist" },
    { id: "z54b7qAB7p0", title: "Bam Bam", artist: "Unknown Artist" },
    { id: "oz0Oz5tBOg8", title: "MONTERO (Call Me By Your Name)", artist: "Unknown Artist" },
    { id: "NLSq2PV2WNg", title: "Head & Heart (feat. MNEK)", artist: "Unknown Artist" },
    { id: "W3Ad0K11mcM", title: "RITMO (Bad Boys For Life)", artist: "Unknown Artist" },
    { id: "tJttoZEbvYg", title: "One Right Now", artist: "Unknown Artist" },
    { id: "rYPQtWOcGmQ", title: "The Middle", artist: "Unknown Artist" },
    { id: "DcDbKDAb7go", title: "What Do You Mean?", artist: "Unknown Artist" },
    { id: "yIQcsvKnxqw", title: "You", artist: "Unknown Artist" },
    { id: "t31xgKtLjwo", title: "no tears left to cry", artist: "Unknown Artist" },
    { id: "3mWbRB3Y4R8", title: "Don't You Worry Child", artist: "Unknown Artist" },
    { id: "VcNFJE6k2_Q", title: "Take My Breath", artist: "Unknown Artist" },
    { id: "X8JH6npiSC4", title: "Promises", artist: "Unknown Artist" },
    { id: "QDQYVFQGkkw", title: "Hold On", artist: "Unknown Artist" },
    { id: "TG2AtaWuikA", title: "10:35", artist: "Unknown Artist" },
    { id: "GRRU11cFNOQ", title: "IDGAF", artist: "Unknown Artist" },
    { id: "xE6NE-N0Pdk", title: "Price Tag", artist: "Unknown Artist" },
    { id: "1ELDTrpecTU", title: "Solo (feat. Demi Lovato)", artist: "Unknown Artist" },
    { id: "y6dw-v4BH-Y", title: "BREAK MY SOUL", artist: "Unknown Artist" },
    { id: "e-9zmBhCfmk", title: "Mood (Remix)", artist: "Unknown Artist" },
    { id: "t4z2NghfBvQ", title: "The Greatest", artist: "Unknown Artist" },
    { id: "VmBoTeLsKfs", title: "I Knew You Were Trouble.", artist: "Unknown Artist" },
    { id: "7GC7eI9c-20", title: "Numb", artist: "Unknown Artist" },
    { id: "gpRxyIPqVDw", title: "Sacrifice", artist: "Unknown Artist" },
    { id: "kb87MlyHHLw", title: "Sweetest Pie", artist: "Unknown Artist" },
    { id: "OK848_DSj6k", title: "It Ain't Me", artist: "Unknown Artist" },
    { id: "gtR09WMSaAw", title: "Overpass Graffiti", artist: "Unknown Artist" },
    { id: "CHSGsoKHIRA", title: "Hold Me Closer", artist: "Unknown Artist" },
    { id: "K4r8PDaOGrA", title: "I'm Good (Blue)", artist: "Unknown Artist" },
    { id: "K_idN3P5_yk", title: "Cheap Thrills", artist: "Unknown Artist" },
    { id: "dHdMAdh4Xgc", title: "Rather Be (feat. Jess Glynne)", artist: "Unknown Artist" },
    { id: "d_4jayID2_A", title: "2 Be Loved (Am I Ready)", artist: "Unknown Artist" },
    { id: "qLboqerzUzI", title: "Hymn for the Weekend (Seeb Remix)", artist: "Unknown Artist" },
    { id: "Nh_bdvA8cVM", title: "Feel So Close", artist: "Unknown Artist" },
    { id: "T_rUtj0Ifos", title: "Electricity", artist: "Unknown Artist" },
    { id: "TfdFUMxRzqU", title: "Roses", artist: "Unknown Artist" },
    { id: "sr7K3jog-DQ", title: "DON'T YOU WORRY", artist: "Unknown Artist" },
    { id: "kbRcMMqjQs0", title: "abc (The Wild Remix)", artist: "Unknown Artist" },
    { id: "yFMwIRdPEMo", title: "Stay With Me", artist: "Unknown Artist" },
    { id: "USR0g4_J4_4", title: "More Than You Know", artist: "Unknown Artist" },
    { id: "HbrX49BZd30", title: "Lights", artist: "Unknown Artist" },
    { id: "t5Mu0yVGph8", title: "Heartbreak Anthem", artist: "Unknown Artist" },
    { id: "kfauyGbueR0", title: "Maybe You’re The Problem", artist: "Unknown Artist" },
    { id: "sBqHtRE-PHI", title: "High", artist: "Unknown Artist" },
  ],

};
export function getRandomTracks(
  mood: keyof MoodPlaylists,
  count: number,
  excludeIds: string[] = []
): Track[] {
  const playlist = MOOD_PLAYLISTS[mood];
  const available = playlist.filter((t) => !excludeIds.includes(t.id));

  if (available.length < count) {
    console.warn(
      `Not enough tracks available for mood "${mood}". Requested: ${count}, Available: ${available.length}`
    );
    return available;
  }
  const shuffled = [...available];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  return shuffled.slice(0, count);
}
export function buildSessionQueue(
  moodPath: Array<keyof MoodPlaylists>,
  distribution: number[]
): Track[] {
  const queue: Track[] = [];
  const usedIds: string[] = [];

  for (let i = 0; i < moodPath.length; i++) {
    const mood = moodPath[i];
    const count = distribution[i];
    const tracks = getRandomTracks(mood, count, usedIds);

    queue.push(...tracks);
    usedIds.push(...tracks.map((t) => t.id));
  }

  return queue;
}
