export type MoodType = 'sad' | 'calm' | 'romantic' | 'happy' | 'energetic';

export interface Song {
  id: string; // YouTube Video ID
  title: string;
  artist: string;
  duration: string;
}

export interface MoodPack {
  id: MoodType;
  name: string;
  emoji: string;
  bg: string;
  surface: string;
  border: string;
  accent: string;
  accentSecondary?: string;
  text: string;
  textMuted: string;
  headingFont: string;
  bodyFont: string;
  borderRadius: string;
  spacing: 'tight' | 'normal' | 'generous';
  playlistName: string;
  description: string;
  songPool: Song[]; // Full pool of songs to sample from
  songs: Song[]; // Will be populated at runtime (12 random songs)
  albumGradient: string;
}
export function sampleSongs(pool: Song[], count: number = 12): Song[] {
  const shuffled = [...pool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
export function getMoodPackWithRandomSongs(mood: MoodType, count: number = 12): MoodPack {
  const pack = { ...moodPacks[mood] };
  pack.songs = sampleSongs(pack.songPool, count);
  return pack;
}

export const moodPacks: Record<MoodType, MoodPack> = {
  sad: {
    id: 'sad',
    name: 'Melancholic',
    emoji: '🌧️',
    bg: '#0d1117',
    surface: '#161b22',
    border: '#21262d',
    accent: '#58a6ff',
    text: '#c9d1d9',
    textMuted: '#6e7681',
    headingFont: '"Playfair Display", serif',
    bodyFont: '"Inter", sans-serif',
    borderRadius: '6px',
    spacing: 'generous',
    playlistName: 'Midnight Reflections',
    description:
      'Songs for the quiet moments when the rain hits the window and the world feels far away.',
    albumGradient: 'linear-gradient(135deg, #161b22 0%, #1a2332 100%)',
    songs: [], // Populated at runtime
    songPool: [
      { id: 'nOeJuoFs6sM', title: 'КАМИН', artist: 'EMIN feat. JONY', duration: '3:05' },
      { id: '-TXtyYZIiWc', title: 'Pastlives', artist: 'sapientdream', duration: '2:34' },
      { id: 'nyuo9-OjNNg', title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', duration: '3:04' },
      { id: 'f0bbDFRYD_A', title: 'changes', artist: 'XXXTENTACION', duration: '2:02' },
      { id: 'IpFX2vq8HKw', title: 'blue', artist: 'yung kai', duration: '3:42' },
      { id: 'Gwg_KYNgu6Y', title: 'Into Your Arms (No Rap)', artist: 'Witt Lowry ft. Ava Max', duration: '2:21' },
      { id: 'RgKAFK5djSk', title: 'See You Again', artist: 'Wiz Khalifa ft. Charlie Puth', duration: '3:58' },
      { id: '60ItHLz5WEA', title: 'Faded', artist: 'Alan Walker', duration: '3:33' },
      { id: '4fqwVBuunxY', title: 'Hurts So Good', artist: 'Astrid S', duration: '3:27' },
      { id: 'KyAcMpQUY5s', title: 'Hope', artist: 'XXXTENTACION', duration: '1:51' },
      { id: 'ALZHF5UqnU4', title: 'Alone', artist: 'Marshmello', duration: '3:20' },
      { id: 'jJPMnTXl63E', title: 'death bed', artist: 'Powfu ft. beabadoobee', duration: '2:54' },
      { id: 'TdrL3QxjyVw', title: 'Summertime Sadness', artist: 'Lana Del Rey', duration: '4:26' },
      { id: 'hbqoaJ8sKsQ', title: 'Broken Angel', artist: 'Arash feat. Helena', duration: '3:25' },
      { id: 'WQq98YPV8yk', title: 'Moral of the Story', artist: 'Ashe', duration: '3:22' },
      { id: 'DKbfBSrjVHA', title: 'Can We Kiss Forever?', artist: 'Kina ft. Adriana Proenza', duration: '3:08' },
      { id: 'yctQRe--q6c', title: 'Love Is Gone', artist: 'SLANDER ft. Dylan Matthew', duration: '5:15' },
      { id: '1e9B31FLT-s', title: 'Experience', artist: 'Ludovico Einaudi', duration: '5:16' },
      { id: 'WgTMeICssXY', title: 'Dandelions', artist: 'Ruth B.', duration: '3:49' },
      { id: 'LTMjsgS_c9M', title: 'Hislerim', artist: 'Serhat Durmus feat. Zerrin', duration: '3:35' },
      { id: 'YykjpeuMNEk', title: 'Hymn For The Weekend', artist: 'Coldplay', duration: '4:21' },
      { id: 'EKkzbbLYPuI', title: 'Carol of the Bells', artist: 'Lindsey Stirling', duration: '3:07' },
      { id: 'PNozaFzqOvI', title: 'Arcade', artist: 'Duncan Laurence ft. FLETCHER', duration: '3:04' },
      { id: 'I-QfPUz1es8', title: 'Bad Liar', artist: 'Imagine Dragons', duration: '4:44' },
      { id: 'y7T3ax7JPwI', title: 'Peaky Blinder', artist: 'Otnicka', duration: '2:32' },
      { id: 'lW9ep22YmlM', title: 'Royalty', artist: 'Egzod & Maestro Chives ft. Neoni', duration: '3:44' },
      { id: 'mRD0-GxqHVo', title: 'Heat Waves', artist: 'Glass Animals', duration: '3:56' },
      { id: 'V1Pl8CzNzCw', title: 'lovely', artist: 'Billie Eilish & Khalid', duration: '3:21' },
      { id: 'Uefu_EU-dW4', title: 'Middle of the Night', artist: 'Elley Duhé', duration: '3:03' },
      { id: 'OlStmta0Vh4', title: 'I Was Never There', artist: 'The Weeknd feat. Gesaffelstein', duration: '4:02' },
      { id: '28W_sotzXUw', title: 'La Câlin', artist: 'Serhat Durmus', duration: '2:53' },
      { id: 'l08Zw-RY__Q', title: 'WILDFLOWER', artist: 'Billie Eilish', duration: '4:22' },
      { id: 'kPa7bsKwL-c', title: 'Die With A Smile', artist: 'Lady Gaga & Bruno Mars', duration: '4:13' },
      { id: '5FSHSfSnjXk', title: 'What Does It Mean To You', artist: 'Carpetman', duration: '4:00' },
      { id: 'DF3XjEhJ40Y', title: 'Love Story', artist: 'Indila', duration: '4:45' },
      { id: 'PWqEPKduGm8', title: 'Infinity', artist: 'Jaymes Young', duration: '3:58' },
      { id: 'd_HlPboLRL8', title: 'Runaway', artist: 'AURORA', duration: '4:10' },
      { id: 'MpLaDn82FtI', title: 'Džanum (Moye Moye)', artist: 'Teya Dora', duration: '2:35' },
      { id: 'm-el0pQLQE4', title: 'childhood', artist: 'Rauf & Faik', duration: '2:05' },
      { id: 'Mc2-YM9Bhu4', title: 'Hislerim', artist: 'Serhat Durmus ft. Zerrin', duration: '3:35' }
    ]
  },
  calm: {
    id: 'calm',
    name: 'Peaceful',
    emoji: '🍃',
    bg: '#f5f0e8',
    surface: '#ede7d9',
    border: '#d4cdbf',
    accent: '#7c9a6e',
    text: '#3d3929',
    textMuted: '#8a8070',
    headingFont: '"DM Sans", sans-serif',
    bodyFont: '"DM Sans", sans-serif',
    borderRadius: '14px',
    spacing: 'normal',
    playlistName: 'Morning Dew',
    description:
      'A gentle collection of sounds to start your day with clarity and peace.',
    albumGradient: 'linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)',
    songs: [], // Populated at runtime
    songPool: [
      { id: 'lbjZPFBD6JU', title: 'Come Away With Me', artist: 'Norah Jones', duration: '3:15' },
      { id: 'E3iq2GS0B80', title: 'Slave To Love (Piano Cover)', artist: 'Bryan Ferry', duration: '4:44' },
      { id: 'bPCdsa7hS7M', title: 'Watermark', artist: 'Enya', duration: '2:26' },
      { id: '7maJOI3QMu0', title: 'River Flows in You', artist: 'Yiruma', duration: '3:30' },
      { id: 'rOLN9T9w9kA', title: 'The Sea', artist: 'Corinne Bailey Rae', duration: '5:48' },
      { id: '1jNNwbuDXsA', title: 'Feel So High', artist: "Des'ree", duration: '3:58' },
      { id: 'QQ84s2uzZ1w', title: 'Ocean Drive', artist: 'Lighthouse Family', duration: '3:52' },
      { id: 'Rk_sAHh9s08', title: 'Return To Innocence', artist: 'Enigma', duration: '4:55' },
      { id: 'KLVq0IAzh1A', title: 'Fields Of Gold', artist: 'Sting', duration: '3:38' },
      { id: 'bTNLYeaL7No', title: 'Songbird', artist: 'Eva Cassidy', duration: '3:48' },
      { id: 'Jl8iYAo90pE', title: 'Caribbean Blue', artist: 'Enya', duration: '3:38' },
      { id: 'MEO6gYCFbr0', title: 'Sailing', artist: 'Christopher Cross', duration: '4:16' },
      { id: 'Ftco75S7ZqE', title: 'Spirit Dances', artist: 'Kashy Keegan', duration: '4:25' },
      { id: 'dVNdTXEJv1A', title: 'Pure Shores', artist: 'All Saints', duration: '3:53' },
      { id: '1TO48Cnl66w', title: 'Thank You', artist: 'Dido', duration: '3:14' },
      { id: 'fd02pGJx0s0', title: 'Sunrise', artist: 'Norah Jones', duration: '3:29' },
      { id: 'rrPUJsZQSkw', title: 'Nine Million Bicycles', artist: 'Katie Melua', duration: '3:15' },
      { id: 'LTrk4X9ACtw', title: 'Orinoco Flow', artist: 'Enya', duration: '3:44' },
      { id: 'j-fWDrZSiZs', title: 'White Flag', artist: 'Dido', duration: '3:42' },
      { id: 'DmAOBosGlHY', title: 'Morning Has Broken', artist: 'Yusuf / Cat Stevens', duration: '3:20' },
      { id: 'rjOhZZyn30k', title: 'Put Your Records On', artist: 'Corinne Bailey Rae', duration: '3:55' },
      { id: 'KPctA0hT9c8', title: 'Peaceful Easy Feeling', artist: 'Eagles', duration: '4:18' },
      { id: 'VqhCQZaH4Vs', title: 'What A Wonderful World', artist: 'Louis Armstrong', duration: '2:30' },
      { id: 'QDYfEBY9NM4', title: 'Let It Be', artist: 'The Beatles', duration: '4:04' },
      { id: 'd-diB65scQU', title: "Don't Worry Be Happy", artist: 'Bobby McFerrin', duration: '3:52' },
      { id: 'flHo2LFWh2I', title: 'Serenity', artist: 'Kashy Keegan', duration: '3:15' },
      { id: 'GemKqzILV4w', title: 'Chasing Cars', artist: 'Snow Patrol', duration: '3:42' },
      { id: '2rd8VktT8xY', title: 'Over The Rainbow', artist: 'Eva Cassidy', duration: '5:31' },
      { id: 'mer6X7nOY_o', title: 'Somewhere Only We Know', artist: 'Lily Allen', duration: '3:43' },
      { id: 'tO4dxvguQDk', title: "Don't Know Why", artist: 'Norah Jones', duration: '3:03' }
    ]
  },
  romantic: {
    id: 'romantic',
    name: 'Romantic',
    emoji: '🌹',
    bg: '#1a0a10',
    surface: '#2a1520',
    border: '#3d2030',
    accent: '#c4547a',
    accentSecondary: '#d4a574',
    text: '#e8d5dc',
    textMuted: '#9a7585',
    headingFont: '"Cormorant Garamond", serif',
    bodyFont: '"Inter", sans-serif',
    borderRadius: '2px',
    spacing: 'tight',
    playlistName: 'Velvet Hour',
    description:
      'Intimate melodies for hearts that beat in sync.',
    albumGradient: 'linear-gradient(135deg, #2a1520 0%, #3d2030 100%)',
    songs: [], // Populated at runtime
    songPool: [
      { id: 'kPa7bsKwL-c', title: 'Die With A Smile', artist: 'Lady Gaga & Bruno Mars', duration: '4:13' },
      { id: 'GxldQ9eX2wo', title: 'Until I Found You', artist: 'Stephen Sanchez', duration: '2:56' },
      { id: 'jXqf3uqLkkU', title: 'Eternity', artist: 'Alex Warren', duration: '3:25' },
      { id: 'r0c9Q21AfLA', title: 'Belong Together', artist: 'Mark Ambor', duration: '2:33' },
      { id: 'e1mOmdykmwI', title: 'I Think They Call This Love', artist: 'Elliot James Reay', duration: '3:14' },
      { id: 'xLYtdCdkuMI', title: 'we hug now', artist: 'sydney rose', duration: '4:09' },
      { id: 'tKml80alH3Y', title: 'Stargazing', artist: 'Myles Smith', duration: '2:53' },
      { id: 'vx4kLgnFexo', title: 'My Love Mine All Mine', artist: 'Mitski', duration: '2:50' },
      { id: 'fukGbiPuBjU', title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', duration: '3:05' },
      { id: 'KZCGhO3t0DA', title: 'Scared To Start', artist: 'Michael Marcagi', duration: '2:40' },
      { id: 'd4iGZ_jP-1U', title: 'Carry You Home', artist: 'Alex Warren', duration: '3:08' },
      { id: 'aKuNwPYACVE', title: 'Espresso', artist: 'Sabrina Carpenter', duration: '2:56' },
      { id: '_-YjO6KfEMk', title: 'Those Eyes', artist: 'New West', duration: '4:35' },
      { id: 'Ms-xidSx0Ek', title: 'Cozy', artist: 'Jeremy Zucker, Lauv & Alexander 23', duration: '3:12' },
      { id: 'u2ah9tWTkmk', title: 'Ordinary', artist: 'Alex Warren', duration: '3:07' },
      { id: 'pVi9W3OThVw', title: 'Teenage Dream', artist: 'Stephen Dawes', duration: '3:01' },
      { id: '57VMB1IzLKY', title: "Stumblin' In", artist: 'CYRIL', duration: '3:34' },
      { id: 'EzQ-KpvHm60', title: 'The Ballet Girl', artist: 'Aden Foyer', duration: '3:36' },
      { id: 'jKIEUdAMtrQ', title: 'Minefields', artist: 'Faouzia & John Legend', duration: '3:28' },
      { id: 'LPgN4EfzUrU', title: 'Calm Down', artist: 'Rema & Selena Gomez', duration: '4:00' },
      { id: '8hLtlzkoGPk', title: 'Hold Me Closer', artist: 'Elton John & Britney Spears', duration: '3:23' },
      { id: 'hKgl5-lkT8U', title: 'Best Part', artist: 'Daniel Caesar & H.E.R.', duration: '4:04' },
      { id: 'DIKIgjLGf98', title: 'Snap', artist: 'Rosa Linn', duration: '3:14' },
      { id: 'm7XGWGFgQVA', title: "Somebody's Pleasure", artist: 'Aziz Hedra', duration: '3:45' },
      { id: '2qzcHLyv3N0', title: 'The Joker And The Queen', artist: 'Ed Sheeran ft. Taylor Swift', duration: '3:07' },
      { id: 'OM5cVB81aT8', title: 'Hero', artist: 'Charlie Puth', duration: '3:17' },
      { id: 'pkDpOIjCJ78', title: 'Stars in the Sky', artist: 'Alexia', duration: '2:45' },
      { id: '1jO2wSpAoxA', title: 'If the World Was Ending', artist: 'JP Saxe ft. Julia Michaels', duration: '3:59' },
      { id: 'FgS1b2nU8AQ', title: 'Sex, Drugs, Etc.', artist: 'Beach Weather', duration: '3:29' },
      { id: 'ODDRRXMi22E', title: 'i like the way you kiss me', artist: 'Artemas', duration: '2:23' },
      { id: 'H5v3kku4y6Q', title: 'As It Was', artist: 'Harry Styles', duration: '2:46' },
      { id: 'NKzd_YiW9AQ', title: 'What If I Told You That I Love You', artist: 'Ali Gatie', duration: '3:34' },
      { id: '8CEJoCr_9UI', title: 'At My Worst', artist: 'Pink Sweat$', duration: '3:12' },
      { id: 'uPD0QOGTmMI', title: 'Die For You', artist: 'The Weeknd', duration: '4:41' },
      { id: 'jRLLWQCOKV4', title: 'Lovesong', artist: 'beabadoobee', duration: '4:03' },
      { id: 'CMWLX0KXwF4', title: 'No One Dies From Love', artist: 'Tove Lo', duration: '4:48' },
      { id: 'Aw1eOFJiDtE', title: 'Fall In Love Alone', artist: 'Stacey Ryan', duration: '3:42' },
      { id: 'H1hDzq98WIY', title: 'Love Me More', artist: 'Sam Smith', duration: '3:49' },
      { id: 'cvCgv775KRs', title: 'Anyone', artist: 'Justin Bieber', duration: '3:11' },
      { id: 'dgmjeMo_pDY', title: 'Line By Line', artist: 'JP Saxe ft. Maren Morris', duration: '3:33' },
      { id: 'ZmDBbnmKpqQ', title: 'drivers license', artist: 'Olivia Rodrigo', duration: '4:07' },
      { id: 'ruHUEmDfw6A', title: 'Scared of Love', artist: 'Ali Gatie', duration: '2:55' },
      { id: 'yg6Y_1_DJyI', title: 'Hot Stuff', artist: 'Kygo & Donna Summer', duration: '3:17' },
      { id: 'vLfxCE6Vofw', title: 'you', artist: 'CKay', duration: '2:53' },
      { id: 'lznH7FZBBYs', title: 'All We Got', artist: 'Robin Schulz feat. KIDDO', duration: '3:25' },
      { id: 'irQzUJK7zdE', title: 'Heaven', artist: 'Pink Sweat$', duration: '2:50' },
      { id: 'Dbx0ryKmmnc', title: 'Too Close', artist: 'JP Cooper', duration: '3:14' },
      { id: '7Lna4Hu4-AQ', title: 'Butterflies', artist: 'MAX & Ali Gatie', duration: '3:15' },
      { id: 'g5T2tu3Yky4', title: 'Shadow Of Mine', artist: 'Alec Benjamin', duration: '2:56' },
      { id: 'H5RpMywlZ2Q', title: 'Sugar Sweet', artist: 'Benson Boone', duration: '3:17' },
      { id: 'jr47YisIsz8', title: "We're Good", artist: 'Dua Lipa', duration: '3:12' },
      { id: 'NmB9Rq1yVmo', title: 'I Love U', artist: 'The Chainsmokers', duration: '3:11' },
      { id: 'h5WN3pkxPF0', title: 'Baila Conmigo', artist: 'Selena Gomez & Rauw Alejandro', duration: '3:20' },
      { id: '8RvAKRoIDqU', title: 'Diamonds', artist: 'Sam Smith', duration: '3:47' },
      { id: 'pk1btLJQjTw', title: 'Your Love (9PM)', artist: 'ATB x Topic x A7S', duration: '2:31' },
      { id: 'V39V9rQxImc', title: 'close with desires', artist: 'teo glacier', duration: '3:22' },
      { id: '_bptrMV3zHE', title: "You're Mines Still", artist: 'Yung Bleu feat. Drake', duration: '4:18' },
      { id: 'ZW5LkUnCoSE', title: 'New Love', artist: 'Silk City feat. Ellie Goulding', duration: '3:29' },
      { id: 'aXzVF3XeS8M', title: "Love Story (Taylor's Version)", artist: 'Taylor Swift', duration: '4:01' },
      { id: 'fz78HOxOgEY', title: 'Stuck With U', artist: 'Ariana Grande & Justin Bieber', duration: '3:49' },
      { id: 'piOIvNO2M8Q', title: 'ily (i love you baby)', artist: 'Surf Mesa feat. Emilee', duration: '3:02' },
      { id: 'nbc7S3hWlgk', title: 'Lovefool', artist: 'twocolors', duration: '3:11' },
      { id: 'Pkh8UtuejGw', title: 'Señorita', artist: 'Shawn Mendes & Camila Cabello', duration: '3:26' },
      { id: 'mYADDo7x83o', title: 'Hey Stupid, I Love You', artist: 'JP Saxe', duration: '3:01' },
      { id: 'VF-r5TtlT9w', title: 'Adore You', artist: 'Harry Styles', duration: '3:39' },
      { id: '24u3NoPvgMw', title: 'Heather', artist: 'Conan Gray', duration: '3:26' },
      { id: '2Vv-BfVoq4g', title: 'Perfect', artist: 'Ed Sheeran', duration: '4:42' },
      { id: '450p7goxZqg', title: 'All of Me', artist: 'John Legend', duration: '5:08' },
      { id: 'JGwWNGJdvx8', title: 'Shape of You', artist: 'Ed Sheeran', duration: '4:24' },
      { id: 'AJtDXIazrMo', title: 'Love Me Like You Do', artist: 'Ellie Goulding', duration: '4:10' },
      { id: 'bo_efYhYU2A', title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', duration: '3:37' },
      { id: 'lWA2pjMjpBs', title: 'Diamonds', artist: 'Rihanna', duration: '4:43' },
      { id: 'Y2E71oe0aSM', title: '10,000 Hours', artist: 'Dan + Shay & Justin Bieber', duration: '2:56' },
      { id: 'pjTj-_55WZ8', title: 'These Days', artist: 'Rudimental ft. Jess Glynne & Macklemore', duration: '3:52' },
      { id: 'LAdxhHz6Tu4', title: 'Love Again', artist: 'Dua Lipa', duration: '4:19' },
      { id: 'RtlOk0Kz5gQ', title: "It's You", artist: 'Ali Gatie', duration: '3:33' },
      { id: 'lwGEhnl0NxQ', title: 'Wait for You', artist: 'Tom Walker', duration: '3:49' },
      { id: 'n-D1EB74Ckg', title: 'Come & Get It', artist: 'Selena Gomez', duration: '4:50' },
      { id: 'g5qU7p7yOY8', title: 'Love Me Harder', artist: 'Ariana Grande & The Weeknd', duration: '4:11' },
      { id: 'V1bFr2SWP1I', title: 'Somewhere over the Rainbow', artist: 'Israel Kamakawiwoʻole', duration: '3:48' },
      { id: 'nIjVuRTm-dc', title: 'She Will Be Loved', artist: 'Maroon 5', duration: '4:29' },
      { id: 'nmjdaBaZe8Y', title: 'With You', artist: 'Chris Brown', duration: '4:16' },
      { id: 'koJlIGDImiU', title: 'Hero', artist: 'Enrique Iglesias', duration: '4:23' },
      { id: 'vhCEaGWTu10', title: 'Wherever You Are', artist: 'Kodaline', duration: '3:23' },
      { id: 'qUD2GxTeVcI', title: 'Conversations in the Dark', artist: 'John Legend', duration: '3:59' },
      { id: 'ONS51QzCh1Y', title: 'Finally // beautiful stranger', artist: 'Halsey', duration: '3:59' },
      { id: 'SlPhMPnQ58k', title: 'Memories', artist: 'Maroon 5', duration: '3:16' },
      { id: 'qz7tCZE_3wA', title: 'Can We Kiss Forever?', artist: 'Kina ft. Adriana Proenza', duration: '3:09' },
      { id: '1qdo91-z7EQ', title: 'Somebody To Love', artist: 'OneRepublic', duration: '3:04' },
      { id: 'WkDbbb0Lyc4', title: 'Love Someone', artist: 'Lukas Graham', duration: '3:28' },
      { id: 'yG60iRJwmfA', title: 'Sucker', artist: 'Jonas Brothers', duration: '3:02' },
      { id: 'sPoDJoTSpUk', title: 'Shameless', artist: 'Camila Cabello', duration: '3:47' },
      { id: 'vtcBNdIq1ms', title: 'I Belong to You', artist: 'Jacob Lee', duration: '5:49' },
      { id: 'vxQO3i5g48I', title: 'WAIT', artist: 'Hunter Hayes', duration: '3:56' },
      { id: 'muPO1c6pxXg', title: 'Snooze (Acoustic)', artist: 'SZA ft. Justin Bieber', duration: '3:12' },
      { id: 'V3IVdLo-2NM', title: 'feelslikeimfallinginlove', artist: 'Coldplay', duration: '4:21' },
      { id: 'zfbIWWZdtoE', title: 'Life With You', artist: 'Kelsey Hart', duration: '2:40' },
      { id: 'msGuqelopMA', title: 'DAISIES', artist: 'Justin Bieber', duration: '2:57' },
      { id: 'O8WXFI_MSAI', title: 'Camera', artist: 'Ed Sheeran', duration: '3:44' },
      { id: '1lrFsXkT_rM', title: 'Sailor Song', artist: 'Gigi Perez', duration: '3:36' }
    ]
  },
  happy: {
    id: 'happy',
    name: 'Joyful',
    emoji: '☀️',
    bg: '#ffffff',
    surface: '#fff9e6',
    border: '#ffe0b2',
    accent: '#ffb300',
    text: '#4a3b00',
    textMuted: '#8c7d40',
    headingFont: '"Bebas Neue", sans-serif',
    bodyFont: '"Inter", sans-serif',
    borderRadius: '24px',
    spacing: 'normal',
    playlistName: 'Golden Hour',
    description:
      'Radiant vibes to keep your spirit high and your smile wide.',
    albumGradient: 'linear-gradient(135deg, #fff9e6 0%, #ffecb3 100%)',
    songs: [], // Populated at runtime
    songPool: [
      { id: 'LnHZ7_1_LVE', title: '10,000 Hours', artist: 'Dan + Shay & Justin Bieber', duration: '2:48' },
      { id: 'qxCCGcMC1Jk', title: '2002', artist: 'Anne-Marie', duration: '3:08' },
      { id: 'bnVkf-z28YU', title: 'I Like Me Better', artist: 'Lauv', duration: '3:18' },
      { id: 'dW1bkAR1UC4', title: 'Capital Letters', artist: 'Hailee Steinfeld & BloodPop', duration: '3:40' },
      { id: '74yb9E3WY1I', title: 'Beautiful People', artist: 'Ed Sheeran feat. Khalid', duration: '3:18' },
      { id: 'LJrejf8blAA', title: 'ME!', artist: 'Taylor Swift ft. Brendon Urie', duration: '3:15' },
      { id: '0m9icI0AOhw', title: 'Perfect To Me', artist: 'Anne-Marie', duration: '3:20' },
      { id: '9TktpJyH58I', title: 'Big Plans', artist: 'Why Don\'t We', duration: '3:02' },
      { id: 'vis3dxQ0rQs', title: 'Say Love', artist: 'James TW', duration: '3:41' },
      { id: 'CCSGelSCPGE', title: 'I Don\'t Care', artist: 'Ed Sheeran & Justin Bieber', duration: '3:38' },
      { id: 'ow1QqW0jzTo', title: 'Señorita', artist: 'Shawn Mendes & Camila Cabello', duration: '3:12' },
      { id: 'cMqal8F3Ef4', title: 'Never Really Over', artist: 'Katy Perry', duration: '3:43' },
      { id: '7bwzasTLOuo', title: 'This Feeling', artist: 'The Chainsmokers ft. Kelsea Ballerini', duration: '3:18' },
      { id: 'UTz2tOSXt2U', title: 'Sucker for you', artist: 'Matt Terry', duration: '3:28' },
      { id: 'q07RanslaGM', title: 'South of the Border', artist: 'Ed Sheeran ft. Camila Cabello & Cardi B', duration: '3:24' },
      { id: 'yTtcaBZt6ow', title: 'Chasing Fire', artist: 'Lauv', duration: '3:26' },
      { id: '9oBZpybMQTE', title: '17', artist: 'Julia Michaels', duration: '3:35' },
      { id: 'KCIKbE_N_DU', title: 'I Forgot That You Existed', artist: 'Taylor Swift', duration: '2:53' },
      { id: 'LS2ifrLAadU', title: 'Stay', artist: 'Zedd & Alessia Cara', duration: '3:33' },
      { id: 'miDfTKlmD6M', title: 'What Lovers Do', artist: 'Maroon 5 feat. SZA', duration: '3:26' },
      { id: 'E5FZMjWOxpU', title: 'Sixteen', artist: 'Ellie Goulding', duration: '3:22' },
      { id: 'vVqGNfAZb2w', title: 'Liar', artist: 'Camila Cabello', duration: '3:28' },
      { id: 'i95Nlb7kiPo', title: 'Your Song', artist: 'Rita Ora', duration: '3:01' },
      { id: 'VJzcoGmcxEc', title: 'She Looks So Perfect', artist: '5 Seconds of Summer', duration: '3:24' },
      { id: 'CEkTYUe_-cA', title: 'Get To Know You', artist: 'Samantha Harvey', duration: '3:22' },
      { id: 'SY3qEbhZhFA', title: 'Let It Be Me', artist: 'Steve Aoki & Backstreet Boys', duration: '3:45' },
      { id: 'eY4t1Scl6LQ', title: 'LET YOU LOVE ME', artist: 'Rita Ora', duration: '3:37' },
      { id: 'GQrIiqPQ-KY', title: 'Takeaway', artist: 'The Chainsmokers & Illenium ft. Lennon Stella', duration: '3:48' },
      { id: '0_6j0Fi0-LM', title: 'Good As Hell', artist: 'Lizzo & Ariana Grande', duration: '2:59' },
      { id: 'ClhLNUPqv8Q', title: 'New Rules', artist: 'Dua Lipa', duration: '3:41' },
      { id: 'lKdOW0OOBaE', title: 'Your Side Of The Bed', artist: 'Loote', duration: '3:18' },
      { id: 'J1kjdF1nICE', title: 'La Di Da', artist: 'Lennon Stella', duration: '3:30' },
      { id: 'W3fJk1rHOOk', title: '123', artist: 'Jess Glynne', duration: '3:11' },
      { id: 'CVhJYPNK6sI', title: 'Don\'t Start Now', artist: 'Dua Lipa', duration: '3:01' },
      { id: 'tRwMD-hCtjk', title: 'I\'ll Be There', artist: 'Walk Off the Earth', duration: '3:12' },
      { id: 'IZ_QRBCQxa8', title: 'Younger', artist: 'Jonas Blue & HRVY', duration: '3:44' },
      { id: 'HOSzxbQOImA', title: 'Shivers', artist: 'The Vamps', duration: '3:04' },
      { id: 'UlXPdOuNU3Q', title: 'These Days', artist: 'Rudimental ft. Jess Glynne & Macklemore', duration: '3:31' },
      { id: '1RNXYIsmbeY', title: 'If You\'re Over Me', artist: 'Years & Years', duration: '3:10' },
      { id: 'YEWJ3E50pC4', title: 'What I Like About You', artist: 'Jonas Blue ft. Theresa Rex', duration: '3:37' },
      { id: 'MrbHZkHimbo', title: '1950', artist: 'King Princess', duration: '3:52' },
      { id: '0ECuBsqUR7Q', title: 'Can We Pretend', artist: 'P!nk ft. Cash Cash', duration: '3:45' },
      { id: '8KbUubuELPs', title: 'Jesus In LA', artist: 'Alec Benjamin', duration: '2:53' },
      { id: 'YiDeezkO7m8', title: 'One Touch', artist: 'Jess Glynne & Jax Jones', duration: '3:34' },
      { id: 'dusDiKHrCk4', title: 'World Of Our Own', artist: 'Westlife', duration: '3:38' },
      { id: '1H1iysBAzCc', title: 'Always you', artist: 'Louis Tomlinson', duration: '4:44' },
      { id: 'iFJdHDE9cgs', title: 'All The Lies', artist: 'Alok, Felix Jaehn & The Vamps', duration: '3:01' },
      { id: '58VNvx4oLXI', title: 'Ooh Girl', artist: 'Kris Kross Amsterdam & Conor Maynard', duration: '2:50' },
      { id: 'AWxUUTQBZR8', title: 'When You\'re Looking Like That', artist: 'Westlife', duration: '3:53' },
      { id: 'fuI0bEdoF30', title: 'Keep You Mine', artist: 'NOTD & Shy Martin', duration: '2:56' },
      { id: 'fU4kTYsCyxU', title: 'Yung Luv', artist: 'Andrelli & Hearts & Colors', duration: '3:31' },
      { id: '7oBU7d5oenQ', title: 'Good Time', artist: 'Owl City & Carly Rae Jepsen', duration: '3:25' },
      { id: '7EwBuptpfx4', title: 'Too Good To Be True', artist: 'Rhys', duration: '3:22' },
      { id: 'jRbbFb0jnm8', title: 'Lost', artist: 'End of the World feat. Clean Bandit', duration: '3:39' },
      { id: 'Y7ix6RITXM0', title: 'Maps', artist: 'Maroon 5', duration: '3:09' },
      { id: 'digUx01moDE', title: 'Ooh La La', artist: 'Josie Dunne', duration: '2:50' },
      { id: 'UFyR8VWImhQ', title: 'Connection', artist: 'OneRepublic', duration: '2:29' },
      { id: '29O6jyi4n-8', title: 'Medicine', artist: 'Robinson', duration: '3:46' },
      { id: 'm3ycpcWapXk', title: 'Headlights', artist: 'Hellberg & Leona Lewis', duration: '3:24' },
      { id: 'Y-Wqna-hC2Y', title: 'Let It Be Me', artist: 'David Guetta ft. Ava Max', duration: '2:53' },
      { id: 'rF53erGQs6c', title: 'Somebody', artist: 'Sigala, HRVY & Nina Nesbitt', duration: '3:59' },
      { id: 'nGGTnNkaZAg', title: 'Never Knew', artist: 'Layton Greene', duration: '3:27' },
      { id: 'teU3AhSjYv0', title: 'Love You Better', artist: 'John De Sohn ft. Rasmus Hagen', duration: '2:52' },
      { id: 'GY_XRuckkR0', title: 'Somebody I\'m Not', artist: 'Martin Jensen & Bjørnskov', duration: '2:48' },
      { id: 'i_ZUBj2xeq8', title: 'Ready To Love You', artist: 'HEDEGAARD', duration: '3:30' },
      { id: '1Qit1aj6z8U', title: 'Paradise to Me', artist: 'Niko Moon', duration: '3:37' },
      { id: 'mk48xRzuNvA', title: 'Hall of Fame', artist: 'The Script ft. will.i.am', duration: '3:54' },
      { id: 'c9fA8zSxb4g', title: 'My Girl', artist: 'Jackson Penn', duration: '3:00' },
      { id: 'L68gl3VfZZQ', title: 'Wanted', artist: 'NOTD & Daya', duration: '2:41' },
      { id: 'QG0tei7zQX8', title: 'Whenever', artist: 'Kris Kross Amsterdam & The Boy Next Door ft. Conor Maynard', duration: '2:44' },
      { id: 'P466Nq-kjY4', title: 'Hot N\'Cold', artist: 'Katy Perry', duration: '3:39' },
      { id: '1hZSulcsImQ', title: 'My Girl', artist: 'The Temptations', duration: '2:56' },
      { id: 'CJqILnpKdxk', title: 'Clearly', artist: 'Grace VanderWaal', duration: '4:13' },
      { id: 'OVFwTEbjNxU', title: 'Lady', artist: 'Blake Rose', duration: '4:05' },
      { id: '0-CYcrmGBZU', title: 'Remind Me To Forget', artist: 'Kygo ft. Miguel', duration: '3:38' },
      { id: 'oGxXyxmynGs', title: 'Hold My Hand', artist: 'Jess Glynne', duration: '4:05' },
      { id: 'j7QUvzX4Mt0', title: 'Move On', artist: 'Mike Posner', duration: '3:01' },
      { id: 'M8w-4JEl06I', title: 'Crying In The Sun', artist: 'Faustix & Shannon Rani', duration: '3:17' },
      { id: 'uMHY3gT38KI', title: 'Endless Summer', artist: 'CASHAE ft. Kiddo AI', duration: '3:21' },
      { id: 'OnKl3g3NGDk', title: 'Family', artist: 'The Chainsmokers & Kygo', duration: '3:11' },
      { id: 'CCED4g1dMTQ', title: 'Build Me Up Buttercup', artist: 'The Foundations', duration: '2:55' },
      { id: 'FBxR2uxXcto', title: 'Dancing In The Moonlight', artist: 'Jubel feat. NEIMY', duration: '2:45' },
      { id: '0fTUj9mfnUk', title: 'Best Day of My Life', artist: 'American Authors', duration: '3:13' },
      { id: 'gDhlk7IhZqA', title: 'Back Together', artist: 'Loote', duration: '3:03' },
      { id: 'i9qjQq8gT68', title: 'Best Of Me', artist: 'Blake Rose', duration: '3:28' },
      { id: 'moKoAUZ25lk', title: 'No Matter', artist: 'Basic Tape & Frances', duration: '3:12' },
      { id: 'opPV1-IUmGw', title: 'Viva la Vida', artist: 'Coldplay', duration: '4:02' }
    ]
  },
  energetic: {
    id: 'energetic',
    name: 'Electric',
    emoji: '⚡',
    bg: '#000000',
    surface: '#0a0a0a',
    border: '#1a1a1a',
    accent: '#ccff00',
    text: '#ffffff',
    textMuted: '#666666',
    headingFont: '"Syne", sans-serif',
    bodyFont: '"Inter", sans-serif',
    borderRadius: '0px',
    spacing: 'tight',
    playlistName: 'High Voltage',
    description:
      'High-octane tracks to fuel your drive and keep you moving.',
    albumGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%)',
    songs: [], // Populated at runtime
    songPool: [
      { id: 'Fplgu4VVb94', title: 'Stargazing', artist: 'Myles Smith', duration: '2:53' },
      { id: 'wd9_QCH8Eq4', title: "Don't Start Now", artist: 'Dua Lipa', duration: '3:04' },
      { id: 'eleP7yc9dSY', title: 'Espresso', artist: 'Sabrina Carpenter', duration: '2:56' },
      { id: 'MpOvl2zZscQ', title: 'Fortnight (BLOND:ISH Remix)', artist: 'Taylor Swift', duration: '3:37' },
      { id: 'Hx4nWW9z0ig', title: 'Dance Monkey', artist: 'Tones and I', duration: '3:30' },
      { id: 'peLRPSCeppI', title: 'Moth To A Flame', artist: 'Swedish House Mafia & The Weeknd', duration: '3:54' },
      { id: 'xBKiqNAcCBs', title: 'Makeba (Ian Asher Remix)', artist: 'Jain', duration: '2:06' },
      { id: 'C0k6USrt408', title: "Don't Be Shy", artist: 'Tiësto & Karol G', duration: '2:21' },
      { id: 'gvL1Bz2QVLY', title: 'Dance With Me', artist: 'beabadoobee', duration: '3:46' },
      { id: 'owTWCbq_nSk', title: 'Something Just Like This', artist: 'The Chainsmokers & Coldplay', duration: '4:08' },
      { id: 'njvA03rMHx4', title: 'Safe And Sound', artist: 'Capital Cities', duration: '3:13' },
      { id: 'jVBsM8CM0AE', title: 'i like the way you kiss me', artist: 'Artemas', duration: '2:23' },
      { id: 'J7p4bzqLvCw', title: 'Blinding Lights', artist: 'The Weeknd', duration: '3:22' },
      { id: '8VKD-IlvibI', title: 'Unholy', artist: 'Sam Smith & Kim Petras', duration: '2:37' },
      { id: '950BdJKBhGo', title: 'Shut Down', artist: 'BLACKPINK', duration: '2:56' },
      { id: 'jPe0bX_GtBo', title: 'INDUSTRY BABY', artist: 'Lil Nas X & Jack Harlow', duration: '3:32' },
      { id: 'G1ej5up7JG0', title: 'Shivers', artist: 'Ed Sheeran', duration: '3:28' },
      { id: 'Z1yDjhXIDSc', title: 'Dance The Night', artist: 'Dua Lipa', duration: '2:57' },
      { id: '2NiyrtYegso', title: 'Wake Me Up', artist: 'Avicii', duration: '4:08' },
      { id: 'ZD6rXLXZOEI', title: 'bad guy', artist: 'Billie Eilish', duration: '3:15' },
      { id: 'HaEYUJ2aRHs', title: 'Dynamite', artist: 'BTS', duration: '3:20' },
      { id: 'hJWSZDJb-W4', title: 'Bad Habits', artist: 'Ed Sheeran', duration: '3:51' },
      { id: 'ui7M7j7caHA', title: 'Kiss Me More', artist: 'Doja Cat ft. SZA', duration: '3:29' },
      { id: 'e8WoWk4b3D0', title: 'Levitating', artist: 'Dua Lipa feat. DaBaby', duration: '3:24' },
      { id: '4zsVKROnQfY', title: 'MIDDLE OF THE NIGHT', artist: 'Elley Duhé', duration: '3:05' },
      { id: 'XZ868t23Pb4', title: '7 rings', artist: 'Ariana Grande', duration: '2:59' },
      { id: 'Ztdc7TcPdAA', title: "There's Nothing Holdin' Me Back", artist: 'Shawn Mendes', duration: '3:20' },
      { id: 'xTvyyoF_LZY', title: 'Shape of You', artist: 'Ed Sheeran', duration: '3:54' },
      { id: 'CpTr4USXjQw', title: "Don't Let Me Down", artist: 'The Chainsmokers ft. Daya', duration: '3:29' },
      { id: 'e-S1k9-soT4', title: 'Cold Heart (PNAU Remix)', artist: 'Elton John & Dua Lipa', duration: '3:23' },
      { id: 'n-UIRqgXnGA', title: 'I Like You (A Happier Song)', artist: 'Post Malone & Doja Cat', duration: '3:13' },
      { id: '_GWKkqNoyEA', title: 'Counting Stars', artist: 'OneRepublic', duration: '4:18' },
      { id: 'TaZkqPK0sbw', title: 'My Universe', artist: 'Coldplay x BTS', duration: '3:49' },
      { id: 'inCm3ByI17o', title: 'This Is What You Came For', artist: 'Calvin Harris ft. Rihanna', duration: '3:43' },
      { id: '_GX3D32b3TI', title: "STAR WALKIN'", artist: 'Lil Nas X', duration: '3:31' },
      { id: 'r7zTKRonHXM', title: 'Closer', artist: 'The Chainsmokers ft. Halsey', duration: '4:06' },
      { id: 'ntG3GQdY_Ok', title: 'Light Switch', artist: 'Charlie Puth', duration: '3:06' },
      { id: '88ft3GeEsto', title: 'Miss You', artist: 'Oliver Tree & Robin Schulz', duration: '3:26' },
      { id: 'Yw-vvxnG9Y4', title: 'Burn', artist: 'Ellie Goulding', duration: '3:52' },
      { id: 'ZqYGW8uXL0I', title: 'New Rules', artist: 'Dua Lipa', duration: '3:30' },
      { id: '0ZwRIThLxGA', title: 'Vegas', artist: 'Doja Cat', duration: '3:03' },
      { id: 'wnWxeBfV2ZQ', title: 'About Damn Time', artist: 'Lizzo', duration: '3:12' },
      { id: 'v16qZcBllUU', title: 'Sorry', artist: 'Justin Bieber', duration: '3:21' },
      { id: 'NaaiI1y9QIo', title: 'Break My Heart', artist: 'Dua Lipa', duration: '3:42' },
      { id: 'tYvFa2ARD24', title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', duration: '4:30' },
      { id: 'tWIJFhZ69_U', title: 'The Motto', artist: 'Tiësto & Ava Max', duration: '2:45' },
      { id: 'sWMk8dwljFU', title: 'Shake It Off', artist: 'Taylor Swift', duration: '3:40' },
      { id: 'y4FiCl-tUJc', title: 'Demons', artist: 'Imagine Dragons', duration: '2:58' },
      { id: 'NNCBq0JHXsU', title: 'Butter', artist: 'BTS', duration: '2:45' },
      { id: 'XWCPbRsMb0Q', title: 'One Kiss', artist: 'Calvin Harris & Dua Lipa', duration: '3:35' },
      { id: 'mG5jXd3MlE0', title: 'feelslikeimfallinginlove', artist: 'Coldplay', duration: '3:58' },
      { id: 'c5l4CGQozWY', title: 'Work from Home', artist: 'Fifth Harmony ft. Ty Dolla $ign', duration: '3:35' },
      { id: 'f0dYb6nrVY4', title: 'Ferrari', artist: 'James Hype & Miggy Dela Rosa', duration: '3:07' },
      { id: '6nJuUdc2qNg', title: 'Roar', artist: 'Katy Perry', duration: '3:44' },
      { id: 'LRPGqNeav_M', title: 'Titanium', artist: 'David Guetta feat. Sia', duration: '4:06' },
      { id: 'Yegn0dZ-BfY', title: 'Physical', artist: 'Dua Lipa', duration: '3:14' },
      { id: 'n6N1_sxlBU8', title: 'We Found Love', artist: 'Rihanna ft. Calvin Harris', duration: '3:36' },
      { id: 'mVw5KiGwqaQ', title: 'Rockabye', artist: 'Clean Bandit ft. Sean Paul & Anne-Marie', duration: '4:12' },
      { id: 'z54b7qAB7p0', title: 'Bam Bam', artist: 'Camila Cabello ft. Ed Sheeran', duration: '3:27' },
      { id: 'oz0Oz5tBOg8', title: 'MONTERO (Call Me By Your Name)', artist: 'Lil Nas X', duration: '2:18' },
      { id: 'NLSq2PV2WNg', title: 'Head & Heart', artist: 'Joel Corry feat. MNEK', duration: '2:47' },
      { id: 'W3Ad0K11mcM', title: 'RITMO', artist: 'The Black Eyed Peas & J Balvin', duration: '3:35' },
      { id: 'tJttoZEbvYg', title: 'One Right Now', artist: 'Post Malone & The Weeknd', duration: '3:13' },
      { id: 'rYPQtWOcGmQ', title: 'The Middle', artist: 'Zedd, Maren Morris & Grey', duration: '3:05' },
      { id: 'DcDbKDAb7go', title: 'What Do You Mean?', artist: 'Justin Bieber', duration: '3:26' },
      { id: 'yIQcsvKnxqw', title: 'You', artist: 'Regard, Troye Sivan & Tate McRae', duration: '3:54' },
      { id: 't31xgKtLjwo', title: 'no tears left to cry', artist: 'Ariana Grande', duration: '3:26' },
      { id: '3mWbRB3Y4R8', title: "Don't You Worry Child", artist: 'Swedish House Mafia', duration: '3:33' },
      { id: 'VcNFJE6k2_Q', title: 'Take My Breath', artist: 'The Weeknd', duration: '3:41' },
      { id: 'X8JH6npiSC4', title: 'Promises', artist: 'Calvin Harris & Sam Smith', duration: '3:34' },
      { id: 'QDQYVFQGkkw', title: 'Hold On', artist: 'Justin Bieber', duration: '2:51' },
      { id: 'TG2AtaWuikA', title: '10:35', artist: 'Tiësto ft. Tate McRae', duration: '2:53' },
      { id: 'GRRU11cFNOQ', title: 'IDGAF', artist: 'Dua Lipa', duration: '3:38' },
      { id: 'xE6NE-N0Pdk', title: 'Price Tag', artist: 'Jessie J ft. B.o.B', duration: '3:42' },
      { id: '1ELDTrpecTU', title: 'Solo', artist: 'Clean Bandit feat. Demi Lovato', duration: '3:43' },
      { id: 'y6dw-v4BH-Y', title: 'BREAK MY SOUL', artist: 'Beyoncé', duration: '4:39' },
      { id: 'e-9zmBhCfmk', title: 'Mood (Remix)', artist: '24kGoldn ft. Justin Bieber & J Balvin', duration: '3:13' },
      { id: 't4z2NghfBvQ', title: 'The Greatest', artist: 'Sia ft. Kendrick Lamar', duration: '3:31' },
      { id: 'VmBoTeLsKfs', title: 'I Knew You Were Trouble.', artist: 'Taylor Swift', duration: '3:40' },
      { id: '7GC7eI9c-20', title: 'Numb', artist: 'Marshmello & Khalid', duration: '2:36' },
      { id: 'gpRxyIPqVDw', title: 'Sacrifice', artist: 'The Weeknd', duration: '3:09' },
      { id: 'kb87MlyHHLw', title: 'Sweetest Pie', artist: 'Megan Thee Stallion & Dua Lipa', duration: '3:22' },
      { id: 'OK848_DSj6k', title: "It Ain't Me", artist: 'Kygo & Selena Gomez', duration: '3:41' },
      { id: 'gtR09WMSaAw', title: 'Overpass Graffiti', artist: 'Ed Sheeran', duration: '3:57' },
      { id: 'CHSGsoKHIRA', title: 'Hold Me Closer', artist: 'Elton John & Britney Spears', duration: '3:23' },
      { id: 'K4r8PDaOGrA', title: "I'm Good (Blue)", artist: 'David Guetta & Bebe Rexha', duration: '2:56' },
      { id: 'K_idN3P5_yk', title: 'Cheap Thrills', artist: 'Sia ft. Sean Paul', duration: '3:31' },
      { id: 'dHdMAdh4Xgc', title: 'Rather Be', artist: 'Clean Bandit feat. Jess Glynne', duration: '3:48' },
      { id: 'd_4jayID2_A', title: '2 Be Loved (Am I Ready)', artist: 'Lizzo', duration: '3:08' },
      { id: 'qLboqerzUzI', title: 'Hymn for the Weekend (Seeb Remix)', artist: 'Coldplay', duration: '3:33' },
      { id: 'Nh_bdvA8cVM', title: 'Feel So Close', artist: 'Calvin Harris', duration: '3:28' },
      { id: 'T_rUtj0Ifos', title: 'Electricity', artist: 'Silk City & Dua Lipa ft. Diplo & Mark Ronson', duration: '3:59' },
      { id: 'TfdFUMxRzqU', title: 'Roses', artist: 'The Chainsmokers ft. ROZES', duration: '3:46' },
      { id: 'sr7K3jog-DQ', title: "DON'T YOU WORRY", artist: 'Black Eyed Peas, Shakira & David Guetta', duration: '3:15' },
      { id: 'kbRcMMqjQs0', title: 'abc (The Wild Remix)', artist: 'Gayle', duration: '3:03' },
      { id: 'yFMwIRdPEMo', title: 'Stay With Me', artist: 'Sam Smith', duration: '3:50' },
      { id: 'USR0g4_J4_4', title: 'More Than You Know', artist: 'Axwell Λ Ingrosso', duration: '3:23' },
      { id: 'HbrX49BZd30', title: 'Lights', artist: 'Ellie Goulding', duration: '3:31' },
      { id: 't5Mu0yVGph8', title: 'Heartbreak Anthem', artist: 'Galantis, David Guetta & Little Mix', duration: '3:04' },
      { id: 'kfauyGbueR0', title: "Maybe You're The Problem", artist: 'Ava Max', duration: '3:11' },
      { id: 'sBqHtRE-PHI', title: 'High', artist: 'Ava Max', duration: '2:56' },
      { id: 'kni8-A1Eu3I', title: 'Deep In Your Love', artist: 'Alok & Bebe Rexha', duration: '2:25' },
      { id: 'tvlrveiqDhc', title: 'Rain On Me', artist: 'Lady Gaga & Ariana Grande', duration: '3:03' },
      { id: 'a909uxd3GWg', title: 'Stay The Night', artist: 'Zedd ft. Hayley Williams', duration: '3:38' },
      { id: 'lGOF_Zh0t58', title: 'Moves Like Jagger', artist: 'Maroon 5 ft. Christina Aguilera', duration: '3:22' },
      { id: 's438WudduuE', title: 'iPad', artist: 'The Chainsmokers', duration: '3:23' },
      { id: 'l3sjUvgLNuk', title: 'Run', artist: 'OneRepublic', duration: '3:11' },
      { id: 'AfD4CZPWN-0', title: '2 Die 4', artist: 'Tove Lo', duration: '3:06' },
      { id: 'PSIy0JM6u2A', title: 'Praising You', artist: 'Rita Ora feat. Fatboy Slim', duration: '2:45' },
      { id: 'guSyeokX1Uw', title: 'Feels', artist: 'Calvin Harris ft. Pharrell, Katy Perry & Big Sean', duration: '3:44' },
      { id: 'd-KzqaR9aF8', title: 'Ocean Avenue', artist: 'Yellowcard', duration: '3:47' },
      { id: 's6dfao4BD9E', title: 'Lil Boo Thang (Galantis Remix)', artist: 'Paul Russell', duration: '2:10' }
    ]
  }
};
